### ISSUE TITLE
Terrafirmacraft question

### ISSUE THREAD

**Issue by Dulciphi** [ProjectZulu/JustAnotherSpawner#125]
Hello. I was really hoping to use JAS to fix spawns in TFC but I'm confused at the crash I keep getting when generating a new world. Sometimes I'm able to generate - most of the time I'm not. 

Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.world.gen.structure.MapGenStructure.func_143027_a(MapGenStructure.java:242)
	at net.minecraft.world.gen.structure.MapGenStructure.func_75048_a(MapGenStructure.java:104)
	at jas.spawner.modern.spawner.biome.structure.StructureInterpreterOverworldStructures.isLocationStructure(StructureInterpreterOverworldStructures.java:101)
	at jas.spawner.modern.spawner.biome.structure.StructureInterpreterOverworldStructures.areCoordsStructure(StructureInterpreterOverworldStructures.java:60)
	at jas.spawner.modern.spawner.biome.structure.StructureHandler.getStructureSpawnList(StructureHandler.java:67)
	at jas.spawner.modern.spawner.biome.structure.StructureHandlerRegistry.getSpawnListAt(StructureHandlerRegistry.java:82)
	at jas.spawner.modern.spawner.creature.entry.BiomeSpawnListRegistry.getSpawnListEntryToSpawn(BiomeSpawnListRegistry.java:165)
	at jas.spawner.modern.spawner.CustomSpawner.spawnCreaturesInChunks(CustomSpawner.java:110)
	at jas.spawner.modern.spawner.SpawnerTicker.performSpawningInWorld(SpawnerTicker.java:77)
	at jas.spawner.modern.spawner.SpawnerTicker.serverTick(SpawnerTicker.java:46)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_727_SpawnerTicker_serverTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:536)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

What's confusing me is that there's no structures that I know of. The crash occurs regardless of whether the compat addon-1.2.0 is included or not. I'm not sure if it's structure related, setting related ..or just an outright incompatibility with TFC. 

[Full log](http://paste.ee/p/Ez63w)

PS. It seems that loading the world that crashed on creation works. 
Generate a new world = crash.
Restart Minecraft and load the world that just crashed = loads without a hitch.

**Comment by Crudedragos** [comment]
The vanilla structure components are included inside JAS and not the compatibility add on as all players are considered always playing with the Overworld. in hindsight, that may not be a wise assumption.

Related to the Stronghold structure. Although the fault is non-obvious. Something internal to the Structure object I'm handling. 

I will investigate further but I'll be busy the next few weeks.

**Comment by Dulciphi** [comment]
Understood and thanks
