### ISSUE TITLE
Chunk populate Crash

### ISSUE THREAD

**Issue by Nozgo** [ProjectZulu/JustAnotherSpawner#143]
I keep getting crashes on our server when loading new chunks. They sometimes become corrupt and cannot reload that chunk. It is odd, because we can load a lot of chunks and randomly we run into one that crashes the server. If I log back in, and go back away from that chunk, it is fine again. Until I load another random chunk it doesn't like. I am running MC 1.7.10 with JAS 0.17.2, and 43 other mods on Forge version "forge-1.7.10-10.13.2.1346". I will paste the crash log below - 
 [23:48:39] [Server thread/INFO] [JustAnotherSpawner]: Chunk spawning entity MoCreatures.BigCat of type CREATURE at 284, 76, -1370 (net.minecraft.world.biome.BiomeGenForest.Forest)
[23:48:40] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.terraingen.PopulateChunkEvent$Populate@2abb9bc7:
java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Unknown Source) ~[?:1.8.0_45]
        at jas.spawner.modern.spawner.CustomSpawner.performWorldGenSpawning(CustomSpawner.java:206) ~[CustomSpawner.class:?]
        at jas.spawner.modern.spawner.ChunkSpawner.performChunkSpawning(ChunkSpawner.java:51) ~[ChunkSpawner.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_342_ChunkSpawner_performChunkSpawning_Populate.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
        at net.minecraftforge.event.terraingen.TerrainGen.populate(TerrainGen.java:36) [TerrainGen.class:?]
        at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:422) [aqz.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279) [ms.class:?]
        at fastcraft.a.d.a(F:84) [fastcraft-1.21.jar:?]
        at fastcraft.Hooks.r(F:137) [fastcraft-1.21.jar:?]
        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040) [apx.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
        at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
        at plantmegapack.worldgen.PMPSpawnLocation.getBlockInfo(PMPSpawnLocation.java:1423) [PMPSpawnLocation.class:?]
        at plantmegapack.worldgen.PMPGenBase.spawnPlantCluster(PMPGenBase.java:78) [PMPGenBase.class:?]
        at plantmegapack.worldgen.PMPWorldGenerator.generateSurface(PMPWorldGenerator.java:99) [PMPWorldGenerator.class:?]
        at plantmegapack.worldgen.PMPWorldGenerator.generate(PMPWorldGenerator.java:46) [PMPWorldGenerator.class:?]
        at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:106) [GameRegistry.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) [ms.class:?]
        at fastcraft.a.d.a(F:84) [fastcraft-1.21.jar:?]
        at fastcraft.Hooks.r(F:137) [fastcraft-1.21.jar:?]
        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040) [apx.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
        at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
        at plantmegapack.worldgen.PMPSpawnLocation.getBlockInfo(PMPSpawnLocation.java:1423) [PMPSpawnLocation.class:?]
        at plantmegapack.worldgen.PMPGenBase.spawnPlantCluster(PMPGenBase.java:78) [PMPGenBase.class:?]
        at plantmegapack.worldgen.PMPWorldGenerator.generateSurface(PMPWorldGenerator.java:99) [PMPWorldGenerator.class:?]
        at plantmegapack.worldgen.PMPWorldGenerator.generate(PMPWorldGenerator.java:46) [PMPWorldGenerator.class:?]
        at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:106) [GameRegistry.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) [ms.class:?]
        at fastcraft.a.d.a(F:84) [fastcraft-1.21.jar:?]
        at fastcraft.Hooks.r(F:137) [fastcraft-1.21.jar:?]
        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040) [apx.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
        at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
        at net.minecraft.world.World.func_147460_e(World.java:693) [ahb.class:?]
        at net.minecraft.world.World.func_147459_d(World.java:652) [ahb.class:?]
        at net.minecraft.world.World.func_147444_c(World.java:613) [ahb.class:?]
        at net.minecraft.world.World.markAndNotifyBlock(World.java:488) [ahb.class:?]
        at net.minecraft.world.World.func_147465_d(World.java:466) [ahb.class:?]
        at plantmegapack.worldgen.PMPGenBase.spawnPlant(PMPGenBase.java:232) [PMPGenBase.class:?]
        at plantmegapack.worldgen.PMPGenBase.spawnPlantCluster(PMPGenBase.java:137) [PMPGenBase.class:?]
        at plantmegapack.worldgen.PMPWorldGenerator.generateSurface(PMPWorldGenerator.java:99) [PMPWorldGenerator.class:?]
        at plantmegapack.worldgen.PMPWorldGenerator.generate(PMPWorldGenerator.java:46) [PMPWorldGenerator.class:?]
        at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:106) [GameRegistry.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) [ms.class:?]
        at fastcraft.a.d.a(F:84) [fastcraft-1.21.jar:?]
        at fastcraft.Hooks.r(F:137) [fastcraft-1.21.jar:?]
        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045) [apx.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:313) [mt.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[23:48:40] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[23:48:40] [Server thread/ERROR] [FML]: 0: NORMAL
[23:48:40] [Server thread/ERROR] [FML]: 1: ASM: jas.spawner.modern.spawner.ChunkSpawner@7cc9e97a performChunkSpawning(Lnet/minecraftforge/event/terraingen/PopulateChunkEvent$Populate;)V
[23:48:40] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception getting block type in world
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:631) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Unknown Source) ~[?:1.8.0_45]
        at jas.spawner.modern.spawner.CustomSpawner.performWorldGenSpawning(CustomSpawner.java:206) ~[CustomSpawner.class:?]
        at jas.spawner.modern.spawner.ChunkSpawner.performChunkSpawning(ChunkSpawner.java:51) ~[ChunkSpawner.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_342_ChunkSpawner_performChunkSpawning_Populate.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
        at net.minecraftforge.event.terraingen.TerrainGen.populate(TerrainGen.java:36) ~[TerrainGen.class:?]
        at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:422) ~[aqz.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279) ~[ms.class:?]
        at fastcraft.a.d.a(F:84) ~[fastcraft-1.21.jar:?]
        at fastcraft.Hooks.r(F:137) ~[fastcraft-1.21.jar:?]
        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040) ~[apx.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
        at net.minecraft.world.World.func_147439_a(World.java:345) ~[ahb.class:?]
        at plantmegapack.worldgen.PMPSpawnLocation.getBlockInfo(PMPSpawnLocation.java:1423) ~[PMPSpawnLocation.class:?]
        at plantmegapack.worldgen.PMPGenBase.spawnPlantCluster(PMPGenBase.java:78) ~[PMPGenBase.class:?]
        at plantmegapack.worldgen.PMPWorldGenerator.generateSurface(PMPWorldGenerator.java:99) ~[PMPWorldGenerator.class:?]
        at plantmegapack.worldgen.PMPWorldGenerator.generate(PMPWorldGenerator.java:46) ~[PMPWorldGenerator.class:?]
        at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:106) ~[GameRegistry.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) ~[ms.class:?]
        at fastcraft.a.d.a(F:84) ~[fastcraft-1.21.jar:?]
        at fastcraft.Hooks.r(F:137) ~[fastcraft-1.21.jar:?]
        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040) ~[apx.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
        at net.minecraft.world.World.func_147439_a(World.java:345) ~[ahb.class:?]
        at plantmegapack.worldgen.PMPSpawnLocation.getBlockInfo(PMPSpawnLocation.java:1423) ~[PMPSpawnLocation.class:?]
        at plantmegapack.worldgen.PMPGenBase.spawnPlantCluster(PMPGenBase.java:78) ~[PMPGenBase.class:?]
        at plantmegapack.worldgen.PMPWorldGenerator.generateSurface(PMPWorldGenerator.java:99) ~[PMPWorldGenerator.class:?]
        at plantmegapack.worldgen.PMPWorldGenerator.generate(PMPWorldGenerator.java:46) ~[PMPWorldGenerator.class:?]
        at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:106) ~[GameRegistry.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) ~[ms.class:?]
        at fastcraft.a.d.a(F:84) ~[fastcraft-1.21.jar:?]
        at fastcraft.Hooks.r(F:137) ~[fastcraft-1.21.jar:?]
        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040) ~[apx.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
        at net.minecraft.world.World.func_147439_a(World.java:345) ~[ahb.class:?]
        at net.minecraft.world.World.func_147460_e(World.java:693) ~[ahb.class:?]
        at net.minecraft.world.World.func_147459_d(World.java:652) ~[ahb.class:?]
        at net.minecraft.world.World.func_147444_c(World.java:613) ~[ahb.class:?]
        at net.minecraft.world.World.markAndNotifyBlock(World.java:488) ~[ahb.class:?]
        at net.minecraft.world.World.func_147465_d(World.java:466) ~[ahb.class:?]
        at plantmegapack.worldgen.PMPGenBase.spawnPlant(PMPGenBase.java:232) ~[PMPGenBase.class:?]
        at plantmegapack.worldgen.PMPGenBase.spawnPlantCluster(PMPGenBase.java:137) ~[PMPGenBase.class:?]
        at plantmegapack.worldgen.PMPWorldGenerator.generateSurface(PMPWorldGenerator.java:99) ~[PMPWorldGenerator.class:?]
        at plantmegapack.worldgen.PMPWorldGenerator.generate(PMPWorldGenerator.java:46) ~[PMPWorldGenerator.class:?]
        at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:106) ~[GameRegistry.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) ~[ms.class:?]
        at fastcraft.a.d.a(F:84) ~[fastcraft-1.21.jar:?]
        at fastcraft.Hooks.r(F:137) ~[fastcraft-1.21.jar:?]
        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045) ~[apx.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:313) ~[mt.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625) ~[MinecraftServer.class:?]

**Comment by Crudedragos** [comment]
Closed via 5937dae73a02e1ce06b4f30ae4cad033c8084892
