### ISSUE TITLE
Spawn Cap unreliable.

### ISSUE THREAD

**Issue by DEX47** [ProjectZulu/JustAnotherSpawner#150]
I have my "Spawn Cap" settings below average: 90 total. How did my map spawn over 450 in an area? I must prevent this from happening. How do I enforce Spawn Caps to be true to their value? Is there a despawn enforcement to prevent this? Are Spawn Caps bugged?

15 Ambient
10 Creature
30 Monster
10 Opensky
10 Underground
15 Watercreature

90 Total

**Comment by Dulciphi** [comment]
There's a few things you can do to help locate the problem

Check that JAS has spawned the all of those entities (many mods have their own spawners that need to be turned off in their respective configs. Lycanites and Mo'Creatures are just 2 examples).
 -JAS [commands](https://github.com/ProjectZulu/JustAnotherSpawner/wiki/Commands) are one useful tool (unless you used /jas killall or /jas countcap to get your figure of 450)
-turn on logging in LoggingProperties.cfg

If that IDs JAS as the culprit, please paste links to logs and configs.

If JAS isn't spawning the extras, it could be many things. If you've already checked other mods' spawners, then check to see if there's a particular type of entity or CreatureType that's spawning more than others. Does it spawn like that without JAS?

Lastly, check GlobalProperties.cfg. Are the VANILLA COMPATABILITY settings default? 
(ie "Turn gamerule spawning off on start": false,
  "Empty vanilla spawnlists": true,
  "Disable Vanilla Chunk Spawning": true,)

**Comment by DEX47** [comment]
Will /jas killall remove all or my Custom NPCs?

**Comment by DEX47** [comment]
I eliminated the additional spawning from Mo'Creatures. Vanilla spawning doesn't seem to be doing anything on it's own so I have the CustomSpawn from JAS enabled and vanilla disabled. However I have run into an old issue that caused me to remove JAS before. I am hoping it is a config issue that will resolve things.

I have fish spawning on the ground and inside the ground. Note that I do have Aquatic Abyss mod and that doesn't seem to blend with JAS fully. I finally got the sea serpents to spawn but the don't do so in water. I also have a critical error that crashes my server at times until I remove an entity with NBTexploter. These entities have always been fish spawning with errors. See Crash log below.

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 11/24/15 4:10 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at thehippomaster.aquaticabyss.WaterCreature.func_70645_a(WaterCreature.java:218)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:855)
	at thehippomaster.aquaticabyss.Fish.func_70097_a(Fish.java:71)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:198)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:157)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1561)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at thehippomaster.aquaticabyss.AquaticCreature.func_70071_h_(AquaticCreature.java:112)
	at thehippomaster.aquaticabyss.WaterCreature.func_70071_h_(WaterCreature.java:64)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at thehippomaster.aquaticabyss.WaterCreature.func_70645_a(WaterCreature.java:218)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:855)
	at thehippomaster.aquaticabyss.Fish.func_70097_a(Fish.java:71)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:198)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:157)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1561)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at thehippomaster.aquaticabyss.AquaticCreature.func_70071_h_(AquaticCreature.java:112)
	at thehippomaster.aquaticabyss.WaterCreature.func_70071_h_(WaterCreature.java:64)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: aquaticabyss.fish (thehippomaster.aquaticabyss.CommonFish)
	Entity ID: 4145
	Entity Name: Fish
	Entity's Exact location: -1292.50, 85.00, -14355.50
	Entity's Block location: World: (-1293,85,-14356), Chunk: (at 3,5,12 in -81,-898; contains blocks -1296,0,-14368 to -1281,255,-14353), Region: (-3,-29; contains chunks -96,-928 to -65,-897, blocks -1536,0,-14848 to -1025,255,-14337)
	Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: Wyldlans2
	All players: 1 total; [EntityPlayerMP['Kharon_47'/3945, l='Wyldlans2', x=-1245.54, y=136.00, z=-14309.56]]
	Chunk stats: ServerChunkCache: 1066 Drop: 0
	Level seed: -8154567819696524531
	Level generator: ID 04 - ATG, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-34,64,-91), Chunk: (at 14,4,5 in -3,-6; contains blocks -48,0,-96 to -33,255,-81), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 98504074 game time, 10528399 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 73693 (now: false), thunder time: 47044 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1082966240 bytes (1032 MB) / 4080271360 bytes (3891 MB) up to 4080271360 bytes (3891 MB)
	JVM Flags: 14 total; -Xmn2G -Xss4M -Xms4G -Xmx4G -XX:+UseLargePages -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:+UseBiasedLocking -Xincgc -XX:MaxGCPauseMillis=10 -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:+CMSParallelRemarkEnabled -XX:ParallelGCThreads=10
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 59453, allocated: 0, tallocated: 5120
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 129 mods loaded, 129 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCHIJAAAA	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks] (minecraft.jar) 
	UCHIJAAAA	WitchingGadgetsCore{1.1.9} [Witching Gadgets Core] (minecraft.jar) 
	UCHIJAAAA	OpenModsCore{0.8} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAA	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) 
	UCHIJAAAA	AncientWarfare{2.4.111-beta-MC1.7.10} [Ancient Warfare Core] (ancientwarfare-2.4.111-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAA	AncientWarfareAutomation{2.4.111-beta-MC1.7.10} [Ancient Warfare Automation] (ancientwarfare-2.4.111-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	AncientWarfareNEIPlugin{2.4.111-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (ancientwarfare-2.4.111-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	AncientWarfareNpc{2.4.111-beta-MC1.7.10} [Ancient Warfare NPCs] (ancientwarfare-2.4.111-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	AncientWarfareStructure{2.4.111-beta-MC1.7.10} [Ancient Warfare Structures] (ancientwarfare-2.4.111-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAA	aquaticabyss{1.1.1} [Aquatic Abyss] (AquaticAbyss-1.7.10-1.1.1.jar) 
	UCHIJAAAA	ATG{0.10.0} [Alternate Terrain Generation] (ATG-1.7.10-0.12.0.jar) 
	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	Automagy{0.26.3} [Automagy] (Automagy-1.7.10-0.26.3.jar) 
	UCHIJAAAA	BiblioCraft{1.10.5} [BiblioCraft] (BiblioCraft[v1.10.5][MC1.7.10].jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1390-universal.jar) 
	UCHIJAAAA	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) 
	UCHIJAAAA	Botania{r1.7-207} [Botania] (Botania r1.7-207.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
	UCHIJAAAA	craftguide{1.6.8.2} [CraftGuide] (CraftGuide-1.6.8.2-forge.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d.jar) 
	UCHIJAAAA	props{2.0.2} [Decocraft] (Decocraft-2.0.2_1.7.10.jar) 
	UCHIJAAAA	decorativemarble{Beta 1.1710.3} [Decorative Marble] (decorativemarble-1.1710.3.jar) 
	UCHIJAAAA	decorativechimney{Beta 1.1710.3} [Decorative Chimney] (decorativechimney-1.1710.3.jar) 
	UCHIJAAAA	diversity{ALPHA 1.6.1} [Diversity] (Diversity-1.7.10-Alpha-1.6.1.jar) 
	UCHIJAAAA	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCHIJAAAA	Enchiridion{1.3} [Enchiridion] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCHIJAAAA	Enchiridion2{2.0.2a} [Enchiridion 2] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCHIJAAAA	EnhancedInventories{1.7.10-1.1.8} [Enhanced Inventories] (EnhancedInventories-1.7.10-1.1.8.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJAAAA	enhancedportals{3.0.12} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.12.jar) 
	UCHIJAAAA	exoticbirds{1.0} [Exotic Birds] (Exotic Birds 1.7.10 - 1.0.2c.jar) 
	UCHIJAAAA	extracells{2.2.73} [Extra Cells 2] (ExtraCells-1.7.10-2.2.73b129.jar) 
	UCHIJAAAA	Forestry{3.6.3.20} [Forestry for Minecraft] (forestry_1.7.10-3.6.3.20.jar) 
	UCHIJAAAA	ExtraFood{0.7.0} [Extra Food] (ExtraFood-1.7.10-0.7.25.jar) 
	UCHIJAAAA	ForbiddenMagic{1.7.10-0.57} [Forbidden Magic] (Forbidden Magic-1.7.10-0.57.jar) 
	UCHIJAAAA	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) 
	UCHIJAAAA	redgear_core{2.2.1} [Red Gear Core] (RedGearCore-1.7.10-2.2.1.jar) 
	UCHIJAAAA	redgear_geocraft{2.4.4} [Geocraft] (Geocraft-1.7.10-2.4.4.jar) 
	UCHIJAAAA	GraveStone{2.12.3} [GraveStone] (GraveStone-2.12.4.jar) 
	UCHIJAAAA	GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3] (GrimoireOfGaia3-1.7.10-1.1.2.jar) 
	UCHIJAAAA	Growthcraft{2.2.2} [Growthcraft] (growthcraft-2.2.2-complete.jar) 
	UCHIJAAAA	Growthcraft|Cellar{2.2.2} [Growthcraft Cellar] (growthcraft-2.2.2-complete.jar) 
	UCHIJAAAA	Growthcraft|Apples{2.2.2} [Growthcraft Apples] (growthcraft-2.2.2-complete.jar) 
	UCHIJAAAA	Growthcraft|Bamboo{2.2.2} [Growthcraft Bamboo] (growthcraft-2.2.2-complete.jar) 
	UCHIJAAAA	Growthcraft|Bees{2.2.2} [Growthcraft Bees] (growthcraft-2.2.2-complete.jar) 
	UCHIJAAAA	Growthcraft|Grapes{2.2.2} [Growthcraft Grapes] (growthcraft-2.2.2-complete.jar) 
	UCHIJAAAA	Growthcraft|Hops{2.2.2} [Growthcraft Hops] (growthcraft-2.2.2-complete.jar) 
	UCHIJAAAA	Growthcraft|Rice{2.2.2} [Growthcraft Rice] (growthcraft-2.2.2-complete.jar) 
	UCHIJAAAA	HelpFixer{1.0.7} [HelpFixer] (HelpFixer-1.0.7.jar) 
	UCHIJAAAA	HopperDuctMod{1.3.2} [Hopper Ducts] (hopperductmod-1.7.10-1.3.2.jar) 
	UCHIJAAAA	mod_Invasion{1.1.2} [Invasion] (Invasion_1.1.2_1.7.10.jar) 
	UCHIJAAAA	JourneyMapServer{1.0.5_MC1.7.10} [JourneyMapServer] (JourneyMapServer1.0.5_MC1.7.10.jar) 
	UCHIJAAAA	Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) 
	UCHIJAAAA	MagicBees{1.7.10-2.3.3} [Magic Bees] (magicbees-1.7.10-2.3.3.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.12.7} [MalisisCore] (malisiscore-1.7.10-0.12.7.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.9.4} [Malisis' Doors] (malisisdoors-1.7.10-1.9.4.jar) 
	UCHIJAAAA	mam{1.7.10-1.0.2} [Myths & Monsters Mod] (mam-1.7.10-1.0.2.jar) 
	UCHIJAAAA	Mariculture{1.7.10-1.2.4.2a} [Mariculture] (Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
	UCHIJAAAA	MariTech{1.0} [Marine Technlogy] (Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.31-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre8.92} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre8.92-Base.jar) 
	UCHIJAAAA	ProjRed|Exploration{4.7.0pre8.92} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre8.92-World.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	me{1.3.2.1} [More Enchantments] (MoreEnchantments-1.7.10-1.3.2.1.jar) 
	UCHIJAAAA	AencEx{0.0.1} [AencEx] (MoreEnchantments-1.7.10-1.3.2.1.jar) 
	UCHIJAAAA	Morpheus{1.7.10-1.6.10} [Morpheus] (Morpheus-1.7.10-1.6.10.jar) 
	UCHIJAAAA	numina{0.4.0.87} [Numina] (Numina-0.4.0.87.jar) 
	UCHIJAAAA	OpenMods{0.8} [OpenMods] (OpenModsLib-1.7.10-0.8.jar) 
	UCHIJAAAA	OpenBlocks{1.4.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4.4.jar) 
	UCHIJAAAA	PneumaticCraft{1.12.1-144} [PneumaticCraft] (PneumaticCraft-1.7.10-1.12.1-144-universal.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre8.92} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre8.92-Integration.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.7.0pre8.92} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre8.92-Compat.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre8.92} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre8.92-Integration.jar) 
	UCHIJAAAA	ProjRed|Fabrication{4.7.0pre8.92} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre8.92-Fabrication.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre8.92} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre8.92-Lighting.jar) 
	UCHIJAAAA	RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
	UCHIJAAAA	Roguelike{1.3.6.3} [Roguelike Dungeons] (roguelike-1.7.10-1.3.6.3.jar) 
	UCHIJAAAA	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) 
	UCHIJAAAA	StorageDrawers{1.7.10-1.6.2} [Storage Drawers] (StorageDrawers-1.7.10-1.6.2.jar) 
	UCHIJAAAA	StorageDrawersBop{1.7.10-1.0.3} [Storage Drawers: Biomes O' Plenty Pack] (StorageDrawers-BiomesOPlenty-1.7.10-1.0.3.jar) 
	UCHIJAAAA	StorageDrawersForestry{1.7.10-1.0.5} [Storage Drawers: Forestry Pack] (StorageDrawers-Forestry-1.7.10-1.0.5.jar) 
	UCHIJAAAA	StorageDrawersMisc{1.7.10-1.0.1} [Storage Drawers: Misc Pack] (StorageDrawers-Misc-1.7.10-1.0.1.jar) 
	UCHIJAAAA	UndergroundBiomes{0.7} [Underground Biomes Constructs] (UndergroundBiomesConstructs-1.7.2-0.7.jar) 
	UCHIJAAAA	TaintedMagic{1.1.5.4} [Tainted Magic] (TaintedMagic-1.1.5.4.jar) 
	UCHIJAAAA	ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects] (ThaumcraftMobAspects-1.7.2-2A.jar) 
	UCHIJAAAA	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-53.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJAAAA	TravellersGear{1.16.4} [Traveller's Gear] (TravellersGear-1.7.10-1.16.4.jar) 
	UCHIJAAAA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJAAAA	WitchingGadgets{1.1.9} [Witching Gadgets] (WitchingGadgets-1.7.10-1.1.9.jar) 
	UCHIJAAAA	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	craftingmanager{0.7.4} [Crafting Manager] (zCraftingManager 0.7.5 mc1.7.10.zip) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	JustAnotherSpawner{0.17.6} [Just Another Spawner] (JustAnotherSpawner-0.17.6.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[map_gen_fix:FINISHED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
	Class transformer null safety: all safe
	CoFHCore: -[1.7.10]3.0.3-303
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	NetherOres: -[1.7.10]2.3.0-12
	RedstoneArsenal: -[1.7.10]1.1.1-89
	ThermalDynamics: -[1.7.10]1.1.0-161
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:ON, BC:OFF, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 15; [EntityPlayerMP['Kharon_47'/3945, l='Wyldlans2', x=-1245.54, y=136.00, z=-14309.56]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
